# .github/workflows/main.yml
name: Run Reusable Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  call-hello-world:
    uses: githubactions2-16-WorkFlows/.github/workflows/hello-world.yml@main
    with:
      script_path: './hello.sh'
